# Generated by Django 3.1.5 on 2021-01-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header',
            field=models.CharField(default='Home', max_length=33),
        ),
    ]
