# Generated by Django 3.1.5 on 2021-01-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210125_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_text_one',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text_two',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
